[project]
name = "pomobar-documentation"
version = "1.6.1"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "mkdocs-git-authors-plugin>=0.10.0",
    "mkdocs-material>=9.7.1",
    "mkdocs-minify-plugin>=0.8.0",
]
